global:
  dockerUsername: mm4r54l
  tag: latest
  imagePullPolicy: Always

ingress:
  enabled: true
  host: myapp.127.0.0.1.nip.io
  className: nginx

auth:
  name: auth
  replicas: 1
  port: 3001

apiGateway:
  name: api-gateway
  replicas: 1
  port: 3000

client:
  name: client
  replicas: 1
  port: 80
  env:
    API_URL:

test:
  enabled: true
  targetService: client
  targetPort: 80
