apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mm4r54l/client:v2.0
          imagePullPolicy: Always
          env:
            - name: VITE_API_URL
              value: api
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: client-nginx-config
