apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}  
  labels:
    app: {{ .Values.apiGateway.name }} 
spec:
  replicas: {{ .Values.apiGateway.replicas  }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}  
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
        - name: {{ .Values.apiGateway.name }}
          image: {{ .Values.global.dockerUsername }}/{{ .Values.apiGateway.name }}:{{ .Values.global.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy  }}
          ports:
            - containerPort: {{ .Values.apiGateway.port  }}
          env:
            - name: PORT
              value: '{{ .Values.apiGateway.port  }}'
            - name: AUTH_URL
              value: http://{{ .Values.auth.name }}-svc:{{ .Values.auth.port  }}
          
          livenessProbe:
            httpGet: 
              path: /api
              port: {{ .Values.apiGateway.port  }}
            initialDelaySeconds: 30
            periodSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /api
              port: {{ .Values.apiGateway.port  }}
            initialDelaySeconds: 5
            periodSeconds: 5
            
