apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.name }}-svc
  labels:
    app: {{ .Values.auth.name }}
spec:
  selector:
    app: {{ .Values.auth.name }}
  ports:
    - name: http
      port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}
