apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}  
  labels:
    app: {{ .Values.auth.name }} 
spec:
  replicas: {{ .Values.auth.replicas  }}
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      containers:
        - name: {{ .Values.auth.name }}
          image: {{ .Values.global.dockerUsername }}/{{ .Values.auth.name }}:{{ .Values.global.tag  }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy  }}
          ports:
            - containerPort: {{ .Values.auth.port }}
          env:
            - name: PORT
              value: '{{ .Values.auth.port }}'            
          
          livenessProbe:
            httpGet: 
              path: /api
              port: {{ .Values.auth.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /api
              port: {{ .Values.auth.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            
