apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.client.name }} 
  labels:
    app: {{.Values.client.name }}  
spec:
  replicas: {{.Values.client.replicas }}
  selector:
    matchLabels:
      app: {{.Values.client.name }}
  template:
    metadata:
      labels:
        app: {{.Values.client.name }}
    spec:
      containers:
        - name: {{.Values.client.name }}
          image: {{.Values.global.dockerUsername}}/{{.Values.client.name}}:{{.Values.global.tag }}
          imagePullPolicy: {{.Values.global.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.client.port }}
          
          livenessProbe:
            httpGet: 
              path: /health
              port: {{.Values.client.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.client.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            
          env:
            - name: VITE_API_URL
              value: api          
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: client-nginx-config
