apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}-svc  
  labels:
    app: {{ .Values.client.name }}    
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - name: http
      port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
